# 기본 설정
theme: jekyll-theme-chirpy
lang: ko-KR
timezone: Asia/Seoul
title: SHIN HAN
tagline: 개발 블로그
description: >
  ruukr8080의 개발블로그

# Site Author
author:
  name: "Shin Han"
  email: ruukr8080@gmail.com
  url: "https://ruukr8080.github.io"
  github:
    username: ruukr8080
  social:
    notion:
      url: https://toast1ng.tistory.com/
    links:
      - https://github.com/ruukr8080
      - https://github.com/ruukr8080

webmaster_verifications:
  google: YOUR_GOOGLE_VERIFICATION_CODE
  bing: YOUR_BING_VERIFICATION_CODE
  alexa: YOUR_ALEXA_VERIFICATION_CODE
  yandex: YOUR_YANDEX_VERIFICATION_CODE
  baidu: YOUR_BAIDU_VERIFICATION_CODE
  facebook: YOUR_FACEBOOK_VERIFICATION_CODE

# Web Analytics Settings
analytics:
  google:
    id: YOUR_GOOGLE_ANALYTICS_ID
  goatcounter:
    id: YOUR_GOATCOUNTER_ID
  umami:
    id: YOUR_UMAMI_ID
    domain: YOUR_UMAMI_DOMAIN
  matomo:
    id: YOUR_MATOMO_ID
    domain: YOUR_MATOMO_DOMAIN
  cloudflare:
    id: YOUR_CLOUDFLARE_ANALYTICS_TOKEN

# Pageviews settings
pageviews:
  provider: goatcounter

theme_mode: light
cdn:
  avatar: https://avatars.githubusercontent.com/u/131014787?v=4
  social_preview_image:

comments:
  provider: giscus
  giscus:
    repo: ruukr8080/ruukr8080.github.io
    repo_id:
    category:
    category_id: 
    mapping: comments/2
    strict: 0
    input_position: bottom
    lang: 
    reactions_enabled: 1

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

baseurl: ""
repository: "https://github.com/ruukr8080/ruukr8080.github.io"

# 추가적인 설정들...

# The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

# _posts settings
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - docs
  - tools
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
