# 기본 설정
# theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Seoul
title: Han 
tagline: programer
description: ruukr8080's blog

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-commonmark
  - jekyll-octicons
  - jekyll-default-layout
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num/"



jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/





# Site Author
author: 
  name: Han
  email: ruukr8080@gmail.com
  url: "https://ruukr8080.github.io"

  github:
    username: ruukr8080
  social:
    notion:
      url: https://toast1ng.tistory.com/
    links:
      - https://github.com/ruukr8080

# Pageviews settings
pageviews:
  provider: goatcounter

theme_mode: dark

# cdn:
avatar: assets/img/avatar.png
social_preview_image: assets/img/avatar.png
self_host:
    enabled: true
    env: development

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:


baseurl: ""
repository: "https://github.com/ruukr8080/ruukr8080.github.io"


kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: 
  syntax_highlighter_opts:
    css_class: highlight
    span: 
      line_numbers: ture
    block:
      line_numbers: true
      start_line: 1
   



   
collections:
  tabs:
    output: true
    sort_by: order

sass:
  style: compressed

comments:
  provider: giscus
  giscus:
    repo: ruukr8080/ruukr8080.github.io
    repo_id: R_kgDOMLRatg
    category: Announcements
    category_id: DIC_kwDOMLRats4CgVMI
    toc: true
    

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]



exclude:
  - docs
  - tools
  - "*.config.js"
  - package*.json


