name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main  # or master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main # 액션 필터 브랜치 체크아웃
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@main # 체크아웃
        with:
          node-version: '20'  # Node.js 버전을 명시적으로 지정
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci  # npm install 대신 ci를 사용
          npm run build

      # 빌드된 파일 배포
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public